name: fruits_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  device_preview: ^1.2.0
  smooth_page_indicator: ^2.0.1
  pinput: ^5.0.0
  carousel_slider: ^5.1.2
  google_nav_bar: ^5.0.7
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  onesignal_flutter: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        